import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import { ToastProvider } from "@/components/ui/toast-context";
import AppProvider from "@/app/AppProvider";
import { cookies } from "next/headers";
const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Soul Blog",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get("sessionToken");
  // console.log("RootLayout:", cookieStore.get("sessionToken"));
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <Header /> */}
          <ToastProvider>
            <AppProvider inititalSessionToken={sessionToken?.value}>
              {children}
            </AppProvider>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
